### ISSUE TITLE
Tagged releases and changelog 

### ISSUE THREAD

**Issue by baimafeima** [l0b0/xautolock#2]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by l0b0** [comment]
This repo was created because the original source did not have a publicly available version control repository. I have not done any releases, and don't plan to do any, because I no longer use this software.
